name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          repo-token: ${{ secrets.ALLTHEACTIONS }} 
          configuration-path: ".github/workflows/auto_assign.yml" 
