on:
  pull_request:
    branches:
      - dev

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Reviewer Checklist \n
          - [ ] spelling and grammar \n
          - [ ] successful run of all installation and code chunks \n
          - [ ] sufficient explanation and details for the tutorial content \n
          - [ ] code syntax and naming convention \n
          - [ ] adherence of tutorial format to style guide \n
          - [ ] functional links (inter and intra)
          - [ ] accessible hyperlink text'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
