name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
         config-name: action-release-drafter.yml
         name: CFDE Training Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
=======
        
>>>>>>> 9f2f7c89691f9eebc9e78600ef6e339540e001a6
