name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - latest

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
         config-name: .github/actions/action-release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
